[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.1"
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
wasm-bindgen-test = "0.3.50"
